# Generated by Django 4.2 on 2023-10-30 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('Alertid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionPoint',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('Metricid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('co_concentration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('h2s_concentration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('methane_concentration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ammonia_concentration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('report_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('indicator', models.CharField(max_length=255)),
                ('indicator_id', models.CharField(max_length=255)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='webuser',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('hobby', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
            ],
        ),
    ]
