# Generated by Django 4.2 on 2023-11-04 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': '警报清单', 'verbose_name_plural': '警报清单'},
        ),
        migrations.AlterModelOptions(
            name='detectionpoint',
            options={'verbose_name': '检测点', 'verbose_name_plural': '检测点'},
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'verbose_name': '检测指标', 'verbose_name_plural': '检测指标'},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'verbose_name': '上报数据', 'verbose_name_plural': '上报数据'},
        ),
        migrations.AlterModelOptions(
            name='threshold',
            options={'verbose_name': '阈值设定', 'verbose_name_plural': '阈值设定'},
        ),
        migrations.AlterModelOptions(
            name='webuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='content',
            field=models.CharField(max_length=255, verbose_name='警报内容'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='警报日期'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='警报值'),
        ),
        migrations.AlterField(
            model_name='detectionpoint',
            name='location',
            field=models.CharField(max_length=255, verbose_name='检测点位置'),
        ),
        migrations.AlterField(
            model_name='detectionpoint',
            name='name',
            field=models.CharField(max_length=255, verbose_name='检测点名称'),
        ),
        migrations.AlterField(
            model_name='detectionpoint',
            name='num',
            field=models.CharField(max_length=255, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(max_length=255, verbose_name='指标名称'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='purpose',
            field=models.TextField(verbose_name='指标用途'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='指标单位'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='ammonia_concentration',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='氨气浓度'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='co_concentration',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='一氧化碳浓度'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='h2s_concentration',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='硫化氢浓度'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='methane_concentration',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='甲烷浓度'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='water_level',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='水位高度'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='indicator',
            field=models.CharField(max_length=255, verbose_name='指标名称'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='indicator_id',
            field=models.CharField(max_length=255, verbose_name='指标ID'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='threshold',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='阈值'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='email',
            field=models.CharField(max_length=30, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='hobby',
            field=models.CharField(max_length=30, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='kind',
            field=models.CharField(max_length=30, verbose_name='性格'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='password',
            field=models.CharField(max_length=30, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='用户名'),
        ),
    ]
