# Generated by Django 4.2 on 2023-11-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_alert_options_alter_detectionpoint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='Alertid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detectionpoint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='ammonia_concentration',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='氨气浓度'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='co_concentration',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='一氧化碳浓度'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='h2s_concentration',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='硫化氢浓度'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='methane_concentration',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='甲烷浓度'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='water_level',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='水位高度'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='threshold',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='阈值'),
        ),
    ]
