# Generated by Django 4.2 on 2023-11-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_alert_alertid_alter_detectionpoint_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zt', models.TextField(verbose_name='风机状态')),
            ],
            options={
                'verbose_name': '风机状态',
                'verbose_name_plural': '风机状态',
            },
        ),
    ]
